version: '1.0'
# To run: docker compose up -f docker-compose2 (how to specify file, since there are two?)
# To kill: docker compose down
# Ref: https://docs.docker.com/compose/compose-file/

networks:
  17646-assignment1:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:  

services:
  jenkins-docker:
    image: docker:dind
    volumes: 
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks: 
      17646-assignment1:
        aliases:
          - docker
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    ports: 
      - '2376:2376'
      - '3000:3000'
  jenkins-17646-assignment1:
    build: .
    volumes:
       - jenkins-data:/var/jenkins_home
       - jenkins-docker-certs:/certs/client:ro
    networks:
      - 17646-assignment1
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    ports:
      - '8080:8080'
      - '8081:8081'
      - '50000:50000'
    restart: on-failure  
  sonarqube:
    image: sonarqube:latest
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks: 
      - 17646-assignment1
    ports:
      - '9000:9000'
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_LOGIN={$SONAR_LOGIN}
    platform: linux/amd64